import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

import { SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import NavigationPath from '@/components/navigation-path';
import { Toaster } from '@/components/ui/toaster';

import ClientWrapper from '@/components/client-provider';

const satoshi = localFont({
  src: './fonts/Satoshi-Regular.woff',
  variable: '--font-satoshi',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientWrapper>
      <html lang='en'>
        <body className={`${satoshi.variable} antialiased `}>
          <SidebarProvider className='h-96'>
            <AppSidebar />
            <SidebarInset>
              <main className='h-full w-full flex flex-col'>
                <Toaster />

                <div className='flex items-center w-full p-2 gap-2'>
                  <SidebarTrigger className='p-4' />
                  <NavigationPath />
                </div>
                {children}
              </main>{' '}
            </SidebarInset>
          </SidebarProvider>
        </body>
      </html>
    </ClientWrapper>
  );
}
